### PR TITLE
Add Gil

### PR DESCRIPTION
**Pull request by LuRsT**
Add me please :)

### CODE REVIEW

**Comment by kseistrup** [comment]
@LuRsT the timestamp at the beginning of the line is supposed to be formatted according to [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt). If you replace the `SPACE` between the date and the time with a `T`, you should be safe.

**Comment by LuRsT** [comment]
Gotcha, I got lost trying to convert it the right way that I forgot about the `T`, thanks for the heads up!

**Comment by kseistrup** [comment]
The server is currently responding with “500 Internal Error”.

Sorry for contacting you here, but I'm unsure if you are following my twtxt stream.

**Comment by kseistrup** [comment]
Looks good now! :+1:

**Comment by kseistrup** [comment]
Or, rather: Are you sure your timestamps are ok?

The latest timestamp says “2019-08-26T15:41:19+01:00”, but that time hasn't even arrived yet – it's ~45 minutes from now.

**Comment by kseistrup** [comment]
And right now the timestamp says “2019-08-26T18:00:06+01:00”, which is approximately 1 hour from now.

**Pull request merged**
