### PR TITLE
Add @pwr

### PR DESCRIPTION
**Pull request by rnkn**
Is me.

### CODE REVIEW

**Comment by prologic** [comment]
> Is me.

I literally cannot follow you because your feed's endpoint uses a CA that is unknown to my setup.. Can you fix this? 🙇‍♂️

image￼

**Comment by prologic** [comment]
@rnkn 👆

**Comment by rnkn** [comment]
@prologic it means there's something in your toolchain that doesn't yet support ECC certificates (but probably does if it's updated).

**Comment by prologic** [comment]
> @prologic it means there's something in your toolchain that doesn't yet support ECC certificates (but probably does if it's updated).

Hmmm 🤔 I see, is this a new thing I missed? Our backend is written in Go and typically (at least for twtxt.net) runs on an Alpine Docker container...

**Comment by rnkn** [comment]
Sorry this was my fault. Hadn't done the SSL right. New server, new URL, new SSL.

**Pull request merged**
