### PR TITLE
Update we-are-twtxt.txt

### PR DESCRIPTION
**Pull request by tolstoevsky**
Trying to join the party ^_^

### CODE REVIEW

**Comment by mdom** [comment]
@kseistrup added you to the list. Have fun!

**Comment by kseistrup** [comment]
> @kseistrup added you to the list

The funny thing is: I have _no_ idea how that happened. I was trying to merge the pull-request here, but kept getting a merge conflict, so I just gave up.

Oh well...

**Comment by mdom** [comment]
I'm not even sure why there was a merge conflict?! Very strange indeed...

**Comment by kseistrup** [comment]
There wasn't, but Microsoft Github displayed in yellow that there was and asked me to solve it manually. But nice that everything's fine now.

**Pull request closed without merging**
